#!/usr/bin/env node
/**
 * Write GALLERY.md: every scene in the repo, shown from the built files under docs/ so it
 * renders on GitHub. Animated scenes embed their self-playing SVG (`<name>.anim.svg`) where
 * the build made one; the rest embed the still.
 *
 *   node scripts/gallery-md.mjs            # after `node bin/dotscene.js build`
 */

import { stat, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { compile } from '../src/compile.ts'
import { loadScenes } from '../src/load.ts'

const OUT = resolve('GALLERY.md')
const DOCS = 'docs'

const size = async (file) => {
  try {
    return (await stat(resolve(DOCS, file))).size
  } catch {
    return undefined
  }
}

const kb = (bytes) => (bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.round(bytes / 1024)} kB`)

/** Which section a scene belongs in, by name. Order here is the order on the page. */
const SECTIONS = [
  ['Heroes', 'One-minute looping backgrounds with a moving camera.', (n) => /^(islandHero|ediHero)/.test(n)],
  ['Site art', 'The same animations told to cover a box, and three card constellations, as the site uses them.', (n) => /^art/.test(n)],
  ['The EDI lifecycle, act by act', 'Each act of the EDI hero as its own scene, on its own clock and framing.', (n) => /^edi\d/.test(n)],
  ['Stages', 'The sets, still, for judging a layout on its own.', (n) => /Stage/.test(n)],
  ['The city', 'The first isometric scene: the kit the heroes are built on.', (n) => /^city/.test(n)],
  ['Figures and studies', 'Everything else: the person, the handshake, the smaller experiments.', () => true],
]

const scenes = [...(await loadScenes('scenes')).values()].map(({ scene }) => scene)
const entries = []
for (const scene of scenes) {
  const compiled = compile(scene)
  const [, , w, h] = compiled.resolved.viewBox
  entries.push({
    name: scene.name,
    title: scene.title ?? scene.name,
    animated: compiled.animated,
    wide: w / h >= 2,
    still: await size(`${scene.name}.svg`),
    anim: await size(`${scene.name}.anim.svg`),
    page: await size(`${scene.name}.html`),
    version: scene.version,
  })
}
// The island first: it is the current peak, and the case study is about it.
const rank = (n) => (n.startsWith('islandHero') ? 0 : n.startsWith('ediHero') ? 1 : 2)
entries.sort((a, b) => rank(a.name) - rank(b.name) || a.name.localeCompare(b.name))

// A dark twin or a site copy is the same animation again; one self-playing copy per family is
// plenty for a page to load, so those show their stills and say so.
const TWIN = (n) => /Night$/.test(n) || /^art(Island|Hero)$/.test(n)

const placed = new Set()
const sections = SECTIONS.map(([title, blurb, test]) => {
  const own = entries.filter((e) => !placed.has(e.name) && test(e.name))
  for (const e of own) placed.add(e.name)
  return { title, blurb, entries: own }
}).filter((s) => s.entries.length > 0)

const card = (e) => {
  const playing = e.anim !== undefined && !TWIN(e.name)
  const image = playing ? `${DOCS}/${e.name}.anim.svg` : `${DOCS}/${e.name}.svg`
  const img = e.wide ? `![${e.title}](${image})` : `<img src="${image}" alt="${e.title}" width="360">`
  const facts = []
  if (playing) facts.push(`self-playing SVG, ${kb(e.anim)}`)
  else if (e.anim !== undefined) facts.push(`the same animation as its twin above; shown as a still, [self-playing copy](${DOCS}/${e.name}.anim.svg) ${kb(e.anim)}`)
  else if (e.animated) facts.push('animated on its page; shown here as a still')
  else facts.push('still')
  if (e.page !== undefined) facts.push(`[page](${DOCS}/${e.name}.html)${e.animated ? ' with the runtime' : ''}, ${kb(e.page)}`)
  if (e.still !== undefined) facts.push(`[still](${DOCS}/${e.name}.svg)`)
  if (e.version !== undefined) facts.push(`v${e.version}, earlier versions under [docs/versions](${DOCS}/versions/)`)
  return `### ${e.title}\n\n\`${e.name}\` — ${facts.join(' · ')}\n\n${img}\n`
}

const intro = `# Gallery

Every scene in this repository, as built into [\`docs/\`](${DOCS}/). Nothing here is a screenshot: each
picture is the SVG the compiler wrote, and the animated ones are the timeline baked into the SVG
itself as SMIL, so they play wherever an SVG image renders — including this page on GitHub —
with no script at all. The pages under \`docs/\` play the same animations through the 9 kB
runtime instead, which also keeps dots and strokes a constant size as the camera zooms and
re-stacks parts as they pass one another; the self-playing copies scale everything with the
zoom and keep the resting paint order. See [CASE-STUDY.md](CASE-STUDY.md) for how the heroes
are made.

If a hero's image does not appear on GitHub, its file is over the image proxy's limit; the
still (\`docs/<name>.svg\`) always will, and the page always plays.

This file is generated by \`node scripts/gallery-md.mjs\` after a build. Edit the script, not
the file.
`

const body = sections
  .map((s) => `## ${s.title}\n\n${s.blurb}\n\n${s.entries.map(card).join('\n')}`)
  .join('\n')

await writeFile(OUT, `${intro}\n${body}`)
console.log(`${OUT}: ${entries.length} scenes in ${sections.length} sections`)
